### ISSUE TITLE
Getting error: uncaught typeerror cannot set property 'width' of null when the content contains images

### ISSUE THREAD

**Issue by Debiprasad** [markswindoll/jQuery-Word-Export#4]
I am getting the following error, if the HTML content contains any image: 

Uncaught typeerror: Cannot set property 'width' of null when the content contains images

But if I don't have any images, then I don't see this issue.

**Comment by markswindoll** [comment]
Images should now be working.

**Comment by Debiprasad** [comment]
Sorry for my late reply. I was busy with some other tasks and did not look at it. It works fine now. Thank you.
